// Admin Product Types
export const ADMIN_PRODUCT_LIST_REQUEST = "ADMIN_PRODUCT_LIST_REQUEST";
export const ADMIN_PRODUCT_LIST_SUCCESS = "ADMIN_PRODUCT_LIST_SUCCESS";
export const ADMIN_PRODUCT_LIST_FAIL = "ADMIN_PRODUCT_LIST_FAIL";

export const ADMIN_PRODUCT_DELETE_SUCCESS = "ADMIN_PRODUCT_DELETE_SUCCESS";
export const ADMIN_PRODUCT_DELETE_FAIL = "ADMIN_PRODUCT_DELETE_FAIL";

export const ADMIN_PRODUCT_ADD_REQUEST = "ADMIN_PRODUCT_ADD_REQUEST";
export const ADMIN_PRODUCT_ADD_SUCCESS = "ADMIN_PRODUCT_ADD_SUCCESS";
export const ADMIN_PRODUCT_ADD_FAIL = "ADMIN_PRODUCT_ADD_FAIL";

export const ADMIN_PRODUCT_UPDATE_REQUEST = "ADMIN_PRODUCT_UPDATE_REQUEST";
export const ADMIN_PRODUCT_UPDATE_SUCCESS = "ADMIN_PRODUCT_UPDATE_SUCCESS";
export const ADMIN_PRODUCT_UPDATE_FAIL = "ADMIN_PRODUCT_UPDATE_FAIL";

// Admin Order Types
export const ADMIN_ORDER_LIST_REQUEST = "ADMIN_ORDER_LIST_REQUEST";
export const ADMIN_ORDER_LIST_SUCCESS = "ADMIN_ORDER_LIST_SUCCESS";
export const ADMIN_ORDER_LIST_FAIL = "ADMIN_ORDER_LIST_FAIL";

export const ADMIN_ORDER_UPDATE_REQUEST = "ADMIN_ORDER_UPDATE_REQUEST";
export const ADMIN_ORDER_UPDATE_SUCCESS = "ADMIN_ORDER_UPDATE_SUCCESS";
export const ADMIN_ORDER_UPDATE_FAIL = "ADMIN_ORDER_UPDATE_FAIL";

// Cart Action Types
export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS";
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD";
export const CART_CLEAR_ITEMS = "CART_CLEAR_ITEMS";

// Product Action Types
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR";
export const FETCH_PRODUCTS_LOADING = "FETCH_PRODUCTS_LOADING";

// User Action Types
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";
export const SET_USER = "SET_USER";
